"""edition added as column

Revision ID: 3c40baef93b7
Revises: ef8381a3c641
Create Date: 2024-08-04 15:25:40.676682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3c40baef93b7'
down_revision: Union[str, None] = 'ef8381a3c641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('baselibrary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baselibrary',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=20), nullable=False),
    sa.Column('author', sa.VARCHAR(), nullable=False),
    sa.Column('pub_year', sa.INTEGER(), nullable=False),
    sa.Column('genre', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###
