"""Initial migration

Revision ID: fb0c6bec3081
Revises: 
Create Date: 2024-08-04 11:40:49.938250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fb0c6bec3081'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('baselibrary', 'pub_year',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('baselibrary', 'pub_year',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
